CC = mpicxx
CFLAGS = -g
LDFLAGS = -L$(HOME)/sw/lib
INCLUDE = -I$(HOME)/sw/include
LIB = -lntl -lmpc -lmpfr -lgmp -lm
OUTPUT_A2M = -o $(EXECUTABLE_A2M)
EXECUTABLE_A2M = A2Mult
OUTPUT_A2A = -o $(EXECUTABLE_A2A)
EXECUTABLE_A2A = A2Add
OUTPUT_G2M = -o $(EXECUTABLE_G2M)
EXECUTABLE_G2M = G2Mult
RUNTIME_LIB = -Wl,-rpath=$(HOME)/sw/lib
OPENMP = -openmp


default:
	$(CC) $(INCLUDE) A2Mult.cxx $(OUTPUT_A2M) $(LDFLAGS) $(LIB) $(RUNTIME_LIB) $(OPENMP)
	$(CC) $(INCLUDE) A2Add.cxx $(OUTPUT_A2A) $(LDFLAGS) $(LIB) $(RUNTIME_LIB) $(OPENMP)
	$(CC) $(INCLUDE) G2Mult.cxx $(OUTPUT_G2M) $(LDFLAGS) $(LIB) $(RUNTIME_LIB) $(OPENMP)

clean:
	rm $(EXECUTABLEA2M)
	rm $(EXECUTABLEA2A)