#!/bin/bash
#
# script for mathematica
# 
#PBS -l nodes=1:ppn=1
#PBS -A hpc_startup_obarrett
#PBS -m e
#PBS -M Owen.Barrett@gmail.com
#PBS -q single
#PBS -l walltime=00:10:00
#PBS -o math.o
#PBS -N mathematica

date

dataDir=PolCharOut
# put output in our work directory
cd /work/obarrett
(echo "{"; for each in $dataDir/*; do cat $each; echo ","; done) > temp
sed -i '$s/,$/\}/' temp
sed -i 's/e/\*10\^/g' temp

mkdir -p matho

math -script mathematica.m

gnuplot mathPlot.gnuplot

date

exit 0
